### PR TITLE
Salvage 2 fix / Addon XML update

### PR DESCRIPTION
**Pull request by tehkrizz**
When it doubt, just re-fork the damn the thing.

### CODE REVIEW

**Comment by alphaONE2** [comment]
Please include a bug tracker link for your Addons. You can enable the GitHub issue tracker for your fork on the repo settings page.

**Comment by tehkrizz** [comment]
I had to delete my repo and re-fork just to get the addon.xml to push correctly.

Is it acceptable to link that section to my FFXIAH threads for each addon?

**Comment by alphaONE2** [comment]
It would be better for consistency if you could link to a github issue tracker, but if you really wan't to link somewhere else... I'll ask.

**Comment by tehkrizz** [comment]
How do I pull files from the windower repo into my fork? I've tried the upstream fetches mentioned on this site, and I haven't had any lucked.

**Comment by alphaONE2** [comment]
Click on the Pull Request button, then switch the branches around so you're pulling from Windower/Lua into your fork.

**Comment by tehkrizz** [comment]
Derp, ok. I'll go ahead and add my issue tracker to my fork, and update the addon.xml.

**Comment by alphaONE2** [comment]
OK, things look good now.

**Comment by tehkrizz** [comment]
Thanks

**Pull request merged**
