### PR TITLE
Compensate for extra UI scaling in text functions

### PR DESCRIPTION
**Pull request by trv6**
Quick fix for texts library UI-scale related mouse issues.

### CODE REVIEW

**Comment by z16** [comment]
I'm not sure how I feel about changing those functions globally inside a library. If someone happens to use those functions along with the `texts` library the behavior will suddenly change for them. We should either compensate for it at the precise points where we use the function inside of the `texts` library, or fix it inside LuaCore, which I feel makes more sense. Would you mind if I adjusted LuaCore instead to return properly adjusted values for those two functions?

**Comment by trv6** [comment]
Not at all.

**Comment by qyyyyyyyyyyyyyyyyyyyy** [comment]
lua python java

**Comment by Tny5989** [comment]
Any updates on this issue?  It would be nice to have this fix but I can see how it wouldn't really be a priority.

**Comment by xurion** [comment]
+1
This affects everyone who wants to drag a text block on a 4k screen where Windows applies a 150% scale-up by default, making it near impossible to reorganise smaller text blocks.

**Comment by Chiaia** [comment]
This has been fixed in the last few months. I don't have a pull request # this time but confirmed with Arcon who fixed it in Luacore back then.

**Pull request closed without merging**
