### PR TITLE
libs/strings.lua todec() neg number handling

### PR DESCRIPTION
**Pull request by Antinym**
Added negative number handling for string.todec()

### CODE REVIEW

**Comment by z16** [comment]
In the future please use white spaces instead of `\t` for indentation. I'll fix that and re-commit it this time.

**Comment by z16** [comment]
I removed the entire function because it does the same as `tonumber`. Honestly, I'm not sure why it was even there.

`tonumber` still has an issue with negative numbers and bases other than 10, but I'll fix that today.

**Comment by Antinym** [comment]
Good deal.  I looked at it again and unless there's a need to work with bases higher than 36 I don't see a need for `todec`.  I switched to using `tonumber` a few hours ago.

**Comment by z16** [comment]
Fixed the non-base-10 issues with `tonumber` in _LuaCore 1.7.9.2_, which is currently on dev. Feel free to test it and report if you find anything wrong with it. I had to edit actual Lua code to fix this, so I can't be entirely sure I didn't break something else in the process.

**Comment by Antinym** [comment]
Tested various combinations of bases and string numbers as well as base 10 decimals.  Everything returned the expected results.

**Comment by z16** [comment]
Alright, thanks for that!

**Pull request merged**
