### PR TITLE
Merge pending Arcon's approval

### PR DESCRIPTION
**Pull request by Byrth**

### CODE REVIEW

**Comment by smd111** [comment]
with texts.lua
did you check to make sure that
var = texts.new(settings)
returns the table because when live had the metatable built this way

```
t = {}
local m = {}
meta[t] = m
```

it would cause an error when you tried to check the name with
var.name and var._name

here is the info
https://github.com/Windower/Lua/issues/1170

**Comment by z16** [comment]
That's not even supposed to work. That particular error should already be fixed on live.

Also, I approve!

**Comment by smd111** [comment]
no its not fix today i had to use an old texts(from dev i have not updated it for a week or more i did not realize this fact) file to make it work but i just tried the latest dev texts and its no good

**Comment by z16** [comment]
Post your issue then, I'll review it before merging this. Every add-on that uses texts works fine, so chances are that it's something very specific to a certain feature of the texts library. That, or you're using it incorrectly.

**Comment by smd111** [comment]
never mind i figured out how to do it
i.e.
var = texts.new(settings)
texts.extents(var)

my brain is farting alot lately

**Comment by z16** [comment]
This should also work:

``` lua
var = texts.new('test')
print(var:extents())
```

**Comment by smd111** [comment]
yes i know its just my brain being stupid
please forgive me

**Pull request merged**
