### PR TITLE
posible fix for file_unload function

### PR DESCRIPTION
**Pull request by smd111**
this is my idea for fixing the file unload issue i have been having

Info:
with the current fix that on the dev version;
it works but the job info does not update to the new job till after get_sets is run

so this is my fix i cam up with on my own

### CODE REVIEW

**Comment by Byrth** [comment]
I pushed a new refresh.lua to -dev that should make this work the way you think it should.

**Comment by smd111** [comment]
yes the load unload works like i would like on dev

 but
i just tested it and now 

```
the command gs l <file>
```

is not working

**Comment by Byrth** [comment]
Changed it, now it should work.

**Comment by smd111** [comment]
now its working correctly 
cant wait till its pushed live so i can remove the custom text.lua files from my includes as well as the texts = require('includes/gstexts')

**Comment by Byrth** [comment]
We're going to push it live now.

**Comment by smd111** [comment]
sweet
ill give it a test tomorrow and if i find any bugs ill post a new issue

**Pull request closed without merging**
