### PR TITLE
Shout helper addon

### PR DESCRIPTION
**Pull request by Jandella**
This addons creates an in-game editable text list in which one can set the party job and assign the player to the respective jobs.
It won't shout automatically nor auto-invite.

### CODE REVIEW

**Comment by alphaONE2** [comment]
I'm afraid we can't accept this until you translate your comments to English. This is to ensure that another developer can understand the code should it be necessary for them to fix or modify the Addon.

Any new commits will automatically be picked up by this pull request. Once you've made the necessary changes please leave a comment and we will review the request again.

**Comment by Jandella** [comment]
Sure thing, my bad for mixing languages!
Done comment translation into english

**Comment by alphaONE2** [comment]
OK, everything looks good.

**Comment by z16** [comment]
Make sure to also update the `addons/addons.xml` file and fill it in with the appropriate values for shoutHelper. That is the only way to get metadata to be displayed in the Windower launcher.

**Comment by alphaONE2** [comment]
Bah! I totally forgot about that >.>

**Comment by Jandella** [comment]
Excuse me, I'm still new to this github thing...
Shall I edit the <code>addons/addons.xml</code> and make the pull request?

**Comment by alphaONE2** [comment]
Yes please. addons.xml is how Launcher gets the descriptions and other metadata for addons. We usually require this to be done before we accept a new addon, but I forgot to check.

**Pull request merged**
