### PR TITLE
Delete AutoLockStyle

### PR DESCRIPTION
**Pull request by cantreadcode**
Originally was made to reapply /lockstyle after zoning. Was replaced by SE's own code. Obsolete addon.

### CODE REVIEW

**Comment by trv6** [comment]
I don't know how this is handled, but you'd have to delete the entry in the addons manifest as well.

**Comment by z16** [comment]
As someone who has never used this addon before - does it do anything that `/lockstyle` doesn't? Or is that a full replacement for the addon?

**Comment by zetaepyon** [comment]
I haven't used it myself either, but I guess it also lets you specify the set that you want to /lockstyle. 

The primary purpose though, I think, was to automatically reapply lockstyle each time you zoned, from prior to when lockstyle was persistent across zoning in general.

**Comment by Byrth** [comment]
I did this and also updated addons.lua.

The addon had no functionality that isn't now provided by the game, as far as I can see.

**Pull request closed without merging**
