### PR TITLE
added ability to check state of debug_mode and show_swaps

### PR DESCRIPTION
**Pull request by smd111**

### CODE REVIEW

**Comment by z16** [comment]
Disregarding the content of your code (I don't know about that, Byrth will have to look it over), but you screwed up the tabs in this file. You should use 4-space indentation for all Windower code.

**Comment by smd111** [comment]
im sorry im used to [tab] not spaces i can fix it and re submit if needed(i fixed it below)

and yes i know that byrth gets the final say

**Comment by alphaONE2** [comment]
@smd111: As long as you use a decent editor (basically anything but Notepad) you can configure the editor to insert 4 spaces when you hit tab.

**Comment by smd111** [comment]
i use notepad++

**Comment by alphaONE2** [comment]
<kbd>Settings</kbd>
<kbd>Preferences...</kbd>
<kbd>Language Menu/Tab Settings</kbd>
- [x] Replace by space

**Comment by smd111** [comment]
i just did that

**Comment by alphaONE2** [comment]
@Byrth have you had a chance to look at this?

**Comment by alphaONE2** [comment]
We can't merge this with the treasury changes included, please revert that last commit and submit a separate pull request for it. Once you do that, and @Byrth gives the ok, we can merge this.

**Comment by smd111** [comment]
and i can only fork windower lua not the individual addons
which means i would have to delete and refork ever time i want to make a pull request

**Comment by z16** [comment]
No, you can fork it once and then make multiple branches. The way it works is that there's a main trunk (the official repo) and your personal trunk (or fork). If you wanna make an addition, you make a new branch off your personal trunk, then change whatever you need to and submit a pull request from that branch to the main repo. That way you can have multiple pull requests (one per branch), where each branch is a separate issue you're working on.

**Comment by smd111** [comment]
ok this is not needed any more
gearswap https://github.com/Windower/Lua/pull/1140
treasury https://github.com/Windower/Lua/pull/1139

**Pull request closed without merging**
