### PR TITLE
Create Obiaway

### PR DESCRIPTION
**Pull request by ReaperX**
puts elemental obis away when they are no longer needed to save inventory space.

### CODE REVIEW

**Comment by alphaONE2** [comment]
Can you please create a readme file for this addon. Follow https://github.com/Windower/Lua/blob/master/addons/eval/readme.md as a template.

Also please include the BSD license text in your source as stated at https://github.com/Windower/Lua#readme. We need to begin enforcing this, so I'm starting with this pull request.

**Comment by ReaperX** [comment]
Created the readme and named it Obiaway.readme. Also added the BSD license.

**Comment by z16** [comment]
The readme needs to be readme.md or readme.txt (readme.md takes priority).

**Comment by z16** [comment]
Also, I'm not sure if I'm seeing this correctly, but the addon itself should have the .lua extension:

```
Windower/addons/<addonname>/<addonname>.lua
Windower/addons/<addonname>/readme.md
```

**Comment by ReaperX** [comment]
Sorry I've never used github before. ;( I can't seem to figure out how to create subfolders in my branch, or rename a file.

**Comment by alphaONE2** [comment]
First, you should have the github client installed. If you don't you can get it from http://windows.github.com/. Next, you should have the repository cloned locally on your PC. To do this just click the "Clone in Windows" button at the top of your fork. Now, make any changes you need to make on your local copy which are now just files on your computer. Commit the changes, then sync. There is no need to issue another pull request.

**Comment by ReaperX** [comment]
ok I followed your steps and I think I got it.

**Comment by alphaONE2** [comment]
It didn't pick up the commit, apparently you put the other changes into a different branch, so I will need you to make another pull request. Sorry about that.

**Pull request closed without merging**
