### PR TITLE
new addon: reive

### PR DESCRIPTION
**Pull request by giulianoriccio**
This plugin tracks exp, bayld, momentum scores and bonuses during a reive.

ss

### CODE REVIEW

**Comment by z16** [comment]
Looking good, before I merge it: What does the file data/=) do? Is that meant to be there, or an oversight?

**Comment by giulianoriccio** [comment]
it's there to make gitHub create the "empty" folder

**Comment by z16** [comment]
You could put a default settings.xml in there, would probably be better than a garbage file, since a settings.xml is created anyway.

**Comment by giulianoriccio** [comment]
done

**Comment by giulianoriccio** [comment]
just a question about the settings.xml
what will happen when windower will update the addon? will it overwrite a customized settings.xml with the one in the repository?

**Comment by z16** [comment]
No, it won't be overwritten.

**Pull request merged**
