### PR TITLE
[craft] make bundled recipes higher recipe numbers than their standard equivalents

### PR DESCRIPTION
**Pull request by posimagi**
Move bundled recipes (those that use Bundling Twine, Spindle, etc.) to higher recipe numbers than the standard recipe that makes the basic quantity.

Fix issues with several recipes that erroneously show multiple copies of the bundling guild item.

### CODE REVIEW

**Comment by posimagi** [comment]
Can I get a review on this? Thanks!

**Comment by Byrth** [comment]
Did you make these changes by editing bgwiki and running create_recipes.py?

Recipes are ordered based on the order they show up in bgwiki, because it is just scraping category pages for them. You need to just change the order in the bgwiki crafting category pages and re-run the script to get them into your preferred order. Otherwise your preferred ordering will vanish the next time someone runs the script and updates this.

**Comment by posimagi** [comment]
Did not know that. I will fix it over there. Thanks.

**Comment by Byrth** [comment]
No problem! Let me know when you update the PR by running create_recipes.py

**Comment by posimagi** [comment]
So I updated the wiki, ran into a roadblock trying to run the script since it's python2 and I don't have a suitable environment for running it. Decided it might actually be faster to update it to python3 so I'm working on that in a separate feature branch. I'm guessing that was an issue for someone else already since some of the fixes I made manually to recipes.lua were already reflected in the wiki a few months ago despite not being reflected in the addon.

**Comment by posimagi** [comment]
Created a separate PR #2267 for the repairs made to the create_recipes.py script (which was not runnable in its current state due to pathological input).

**Comment by posimagi** [comment]
This diff will be stacked on top of #2267. Please merge that one first.

**Pull request merged**
