### PR TITLE
Update send.lua

### PR DESCRIPTION
**Pull request by lili-ffxi**
Adjust string processing to reinstate double quotes removed by the command processor.

### CODE REVIEW

**Comment by lili-ffxi** [comment]
Bug found. Will reopen once fixed.

**Comment by lili-ffxi** [comment]
Fixed, I had swapped two arguments because of course I did.

**Comment by zmsl** [comment]
I am attempting to load this version into my XI client and am getting an error when running a simple send

image

Command: "send Altname test"

**Comment by lili-ffxi** [comment]
> I am attempting to load this version into my XI client and am getting an error when running a simple send
> 
> image
> 
> Command: "send Altname test"

This error means that you downloaded the addon manually and tried to run it on windower live. You need windower dev for this to work.

**Pull request merged**
