### PR TITLE
Added ModelSize and Height Addon

### PR DESCRIPTION
**Pull request by SammehFFXI**
Added ModelSize and Height Addon

### CODE REVIEW

**Comment by z16** [comment]
While I'm not opposed to either of the addons, I feel that both could be merged into existing addons, instead of making them separate. _ModelSize_ seems to fit very well with what _TargetInfo_ already does, it displays internal info about entities on the screen. It could just be another row in there.

And _Height_ seems very useful, but I feel it could be incorporated into the _Distance_ addon. It could be a toggleable setting, even with a whitelist to only be used on certain mobs. However this one does seem to warrant its own addon if there's more logic involved (like detecting that the mob is a _Geas Fete_ mob and adjusting display based on that). As simple as it is now, it's merely "vertical distance". The old _Distance_ plugin did support switching between 2D distance (horizontal distance) and 3D distance (diagonal distance). The addon does not have this feature, but it would not be hard to add, and in the same vein the vertical distance could be added as an optional display.

Anyway, these are just ideas. If you still want them to be single addons, I won't stand in the way. Let me know if you want to go that way. In that case I'll start a code review (there are a few things you need to adjust before we can merge this). Also, in the future it's better to make single pull request for each addon.

**Comment by SammehFFXI** [comment]
Very good info and understood.

First note I'm _very_ new to this and I'm picking from other luas to
combine some stuff.  I've been doing this on my own PC and while I'm a
SysAdmin/Network Admin by trait - and have heard a million times over again
GIT and what it is/does/used for - I've never used it myself.

I'm working on a lua I'm calling 'DistancePlus' which does alot of this.  I
can keep the ModelSize as a dev tool only (really only using it as such,
has little value in-game otherwise).

DistancePlus will do the following (and is a replacement for Distance):
1) Display Distance (duh)
2) Have Job Specific / Situation specific color coordination.   For
example:  On Ranger - you could pick from Gun, XBow, or Bow and based on
target distance it will automatically change colors (>25 you can't shoot
for example,  Yellow = Can shoot but no Trueshot bonus,  Green = TrueShot
bonus, Blue = Optimal Trueshot Bonus).
3) Pet addon - shows distance between master and pet.
4) Job ability list - similar to #2 - but per-JA.

It also changes dynamically based on target.model_size which is a huge
delta in where you can stand to cast/shoot/do job abilities.

So with that said - I can merge Distance with Height if you want (simply
making a //height command to display it along-side the Distance Plugin.)
I don't use TargetInfo much - so i can't say I'd merge it. I can just keep
it away.   How would I "withdrawl" the request for these?

the DistancePlus is soon to come.  I'm horribly inefficient at code and
trying to clean it up so it isn't the ugliest thing you ever saw ;)

-Sam

**Comment by alphaONE2** [comment]
Hey, no worries. We were all new to this at one time or another. If you've changed your mind, you can close the PR, by clicking the "Close pull request" button at the bottom of this page.

In either case, these look like reasonable, and useful additions. I wouldn't worry about model size being a dev-related feature; the TargetInfo addon is already quite skewed toward research and development, anyway.

**Comment by alphaONE2** [comment]
Hey, no worries. We were all new to this at one time or another. If you've changed your mind, you can close the PR, by clicking the "Close pull request" button at the bottom of this page.

In either case, these look like reasonable, and useful additions. I wouldn't worry about model size being a dev-related feature; the TargetInfo addon is already quite skewed toward research and development, anyway.

**Comment by alphaONE2** [comment]
Hey, no worries. We were all new to this at one time or another. If you've changed your mind, you can close the PR, by clicking the "Close pull request" button at the bottom of this page.

In either case, these look like reasonable, and useful additions. I wouldn't worry about model size being a dev-related feature; the TargetInfo addon is already quite skewed toward research and development, anyway.

**Pull request closed without merging**
